using SkinCancerDetectionApp.Services.SkinCancerDetectionService.Interfaces;

namespace SkinCancerDetectionApp.Services.SkinCancerDetectionService;

public class SkinCancerDetectionService : ISkinCancerDetectionService
{
}